version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine3.21-perl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - cadraapi
      - cadraapp
    networks:
      - cadra-network
  postgres:
    image: postgres:15-alpine
    container_name: cadra-postgres
    hostname: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /root/app/postgres:/var/lib/postgresql/data
    networks:
      - cadra-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cadra"]
      interval: 30s
      timeout: 10s
      retries: 5

  cadraapi:
    image: kmikhailsbrobrocode/cadra:v0.959
    container_name: cadraapi
    hostname: cadraapi
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVIER_PORT: ${SERVIER_PORT}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      CADRA_REDIRECT_URI: ${CADRA_REDIRECT_URI}
      AUTHORIZATION_URI: ${AUTHORIZATION_URI}
      DASHBOARD_REDIRECT_URI: ${DASHBOARD_REDIRECT_URI}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LIQUIBASE_URL: ${POSTGRES_URL}
      LIQUIBASE_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_PASSWORD: ${POSTGRES_PASSWORD}
      YUKASSA_SHOP_ID: ${YUKASSA_SHOP_ID}
      YUKASSA_SECRET_KEY: ${YUKASSA_SECRET_KEY}
      YUKASSA_SHOP_API_URL: ${YUKASSA_SHOP_API_URL}
      YUKASSA_SHOP_REDIRECT_URL: ${YUKASSA_SHOP_REDIRECT_URL}
      GIGA_CHAT_AUTH_KEY: ${GIGA_CHAT_AUTH_KEY}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - cadra-network
    volumes:
      - /root/app/logs:/logs

  cadraapp:
    image: kmikhailsbrobrocode/cadraapp:v0.943
    container_name: cadraapp
    hostname: cadraapp
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - /root/app/images:/usr/share/nginx/html/images
    networks:
      - cadra-network
    depends_on:
      - cadraapi

networks:
  cadra-network:

volumes:
  cadra-logs:
    driver: local
